name: flutter_hive_tdo
description: Flutter Hive Todo app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  intl: ^0.20.2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  flutter_datetime_picker_plus: ^2.1.0
  animate_do: ^4.2.0
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.5
  lottie: ^2.6.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
